/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rainea_jni_HelloJNI */

#ifndef _Included_com_rainea_jni_HelloJNI
#define _Included_com_rainea_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rainea_jni_HelloJNI
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rainea_jni_HelloJNI_sayHelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
